Localscriptcreator
fsimkovic/pyjob pull request #23
Opened 2018-09-05 15:18 UTC by hlasimpk

Added a local script creator function and test function. 

Would like advice on the doc strings as we're inputting a function and I don't know how to tag it. I'm also just returning the collector object from a `LocalScriptCreator.collector()` so you might have some suggestions about how to rewrite this in a nicer way.

2018-09-05 20:48 UTC, fsimkovic commented
@hlasimpk test cases don't pass

2018-09-05 21:37 UTC, hlasimpk commented
@fsimkovic my pytest install seems to be missing attributes, any idea?

2018-09-06 08:17 UTC, fsimkovic commented
Please add an example to the documentation. This should be documented in `docs/quickstart.rst`.

2018-09-06 08:17 UTC, fsimkovic requested changes

2018-09-06 08:17 UTC, fsimkovic commented on pyjob/tests/test_script.py
> +        assert collector.scripts == [['e c h o   1'], ['e c h o   2'], ['e c h o   3'], ['e c h o   4'], ['e c h o   5']]
What's with the spaces in all `str` objects?

2018-09-06 08:17 UTC, fsimkovic commented on pyjob/tests/test_script.py
> +    def example_function(self, i):
Make this a `@staticmethod`.

2018-09-06 14:14 UTC, hlasimpk commented
Sorted out the test cases and added description to docs

2018-09-07 09:14 UTC, fsimkovic commented
@hlasimpk Please add a `@pytest.skipif` decorator around the `LocalScriptCreator` class on Windows ... check the AppVeyor report above

2018-09-07 10:32 UTC, fsimkovic approved these changes

2018-09-07 10:33 UTC, merged